steps:
  - id: Build Frontend
    name: gcr.io/cloud-builders/docker
    args: [build, -t, gcr.io/$PROJECT_ID/$_SERVICE_NAME-front:$COMMIT_SHA, ., -f, frontend.Dockerfile]

  - id: Run Frontend
    name: gcr.io/cloud-builders/docker
    args: [run, --name, temp, gcr.io/$PROJECT_ID/$_SERVICE_NAME-front:$COMMIT_SHA]

  - id: Gather Static Site
    name: gcr.io/cloud-builders/docker
    args: [cp, temp:/app/.web/_static, /workspace/output]

  - id: Firebase Hosting
    name: gcr.io/$PROJECT_ID/firebase
    args: [deploy, --project=$PROJECT_ID, --only=hosting]    

  - id: Build Backend
    name: gcr.io/cloud-builders/docker
    args: [build, -t, gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA, .]

  - id: Push Backend
    name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA]

  - id: Deploy Backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region
      - $_DEPLOY_REGION
      - --memory
      - $_MEMORY
images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: rotr-app
  _BUCKET_NAME: rotr-app
  _LOAD_BALANCER: rotr-lb
  _DEPLOY_REGION: us-central1
  _MEMORY: 512Mi
