steps:
  # Install project dependencies and build frontend
  - name: python:3.12
    entrypoint: bash
    args:
      - -c
      - |
        pip install --no-cache-dir -r requirements.txt
        export API_URL=https://$_SERVICE_NAME-$PROJECT_NUMBER.$_DEPLOY_REGION.run.app
        reflex export --no-zip --frontend-only

  # Deploy to firebase hosting
  - name: gcr.io/$PROJECT_ID/firebase
    args: 
      - deploy
      - --project=$PROJECT_ID
      - --only=hosting

  # Build backend container
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA, .]

  # Push backend container
  - name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA]

  # Deploy container to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: 
      - gcloud
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --memory=$_MEMORY

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # This is the name of the cloud run service where the backend lives
  _SERVICE_NAME: rotr-app
  _DEPLOY_REGION: us-central1
  _MEMORY: 512Mi

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - rotr-app
