steps:
  - id: Deploy Function
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: 
      - gcloud
      - functions
      - deploy
      - survey-ingest
      - --gen2
      - --region=us-central1
      - --trigger-http
      - --runtime=python312
      - --source=.
      - --entry-point=hello_http
options:
  logging: CLOUD_LOGGING_ONLY